### ISSUE TITLE
Is this still work with the current Rails 7?

### ISSUE THREAD

**Issue by ronald2wing** [jigarius/lando-rails-example#1]
Can you update this repo? Lando has Ruby image now.

**Comment by jigarius** [comment]
Hello! I'm not using Lando anymore. If you use it, I'd invite you to create a pull request for the change that you are proposing.

**Comment by ronald2wing** [comment]
I am using another Docker repo now. I do wish Lando supported Rails, mainly after they supported Ruby. It's been too long since anyone created a Rails Lando recipe.

Thank you for getting back to me.
